server:
  port:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartatmdb
    username: smartatm_user
    password: password3329
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
